/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Greeting } from "./Greeting";
export * as factories from "./factories";
export { Greeting__factory } from "./factories/Greeting__factory";
